version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: travel_agency_db
    environment:
      POSTGRES_USER: ${Database_Username:-postgres}
      POSTGRES_PASSWORD: ${Database_Password:-password}
      POSTGRES_DB: travel_agency
    ports:
      - "5432:5432"
    restart: unless-stopped