# PostgreSQL DataSource (Production)
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_agency?options=-c%20timezone=UTC
spring.datasource.username=${Database_Username:postgres}
spring.datasource.password=${Database_Password:password}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
